version: '3.7'

services:
  reactapp:
    build:
      dockerfile: Dockerfile
    container_name: reactapp
    ports:
      - 80:3000
    networks:
      - frontend
    
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=superroot
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - datadb:/data/db
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superroot
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend

networks:
  backend:
    name: backend
  
  frontend:
    name: frontend

volumes:
  datadb: {}